name: cuti_flutter_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1
  flutter_rounded_date_picker: ^1.0.4
  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  firebase_database: ^3.1.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  double_back_to_close_app: ^1.2.0

  font_awesome_flutter: ^8.8.1
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/user.jpg
    - assets/images/company-logo.png

fonts:
  - family: Poppins
    fonts:
      - assets: assets/fonts/Poppins-Regular.ttf

  - family: Montserrat
    fonts:
      - assets: assets/fonts/Montserrat-Regular.ttf
